import React from 'react';

const About = () => {
    return (
        <div>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
            <p style={{textAlign:"justify"}} className="text-secondary container">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, expedita sit voluptatum quod laboriosam repudiandae id. Quam omnis deserunt atque sequi natus doloremque consectetur blanditiis exercitationem deleniti veniam vel epe facilis placeat officiis odit atque aperiam dolorum a maiores maxime, illum assumenda aspernatur totam illo sunt optio perspiciatis amet laboriosam libero fuga esse! Eum saepe quaerat aliquam nam natus magnam vitae!</p>
        </div>
    );
};

export default About;